---
title: "Explore"
author: "Paul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(drake)
theme_set(theme_light())
```

## EDA

```{r}
loadd(train)
```

```{r}
loadd(cleaned)
```


```{r}
cleaned$train %>% 
  ggplot(aes(target))+
  geom_bar()
```

# Cleaned data
```{r}
skimr::skim(cleaned$test)

```

# Preprocessed Data
```{r}
loadd(preprocessed)
```

```{r}
skimr::skim(preprocessed$test)
```





## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
